pipeline {
  agent none
  environment {
    some_username = credentials("user_name1")
    some_secrettext = credentials("some_secrettext")    
  }
  stages {
    stage('Build') {
        agent any
        steps {
        echo "some_username"
        echo "some_secrettext"
        }
    }
  }  
}
