pipeline {
  agent none
  states {
    stage('Build') {
        agent any

        steps {
          echo 'Hello, check my workspace and I did not checked-out the code from GIT'
        }
    }
  
  }
}

