pipeline {
  agent none
  stages {
    stage('Build') {
        agent any
        /* options {
          skipDefaultCheckout()
        } */
        steps {
          echo 'Hello, check my workspace and I did not checked-out the code from GIT'
        }
    }

  }
}

